// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: generate.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prompt string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Number of tokens to predict (-1 = infinity, -2 = until context filled)
	NPredict int32 `protobuf:"varint,2,opt,name=n_predict,json=nPredict,proto3" json:"n_predict,omitempty"`
	// Context size
	NCtx int32 `protobuf:"varint,3,opt,name=n_ctx,json=nCtx,proto3" json:"n_ctx,omitempty"`
	// Logical batch size for prompt processing
	NBatch int32 `protobuf:"varint,4,opt,name=n_batch,json=nBatch,proto3" json:"n_batch,omitempty"`
	// Number of tokens to keep from initial prompt
	NKeep int32 `protobuf:"varint,5,opt,name=n_keep,json=nKeep,proto3" json:"n_keep,omitempty"`
	// Number of parallel sequences to decode
	NParallel int32 `protobuf:"varint,6,opt,name=n_parallel,json=nParallel,proto3" json:"n_parallel,omitempty"`
	// Group-attention factor
	GrpAttnN int32 `protobuf:"varint,7,opt,name=grp_attn_n,json=grpAttnN,proto3" json:"grp_attn_n,omitempty"`
	// Group-attention width
	GrpAttnW int32 `protobuf:"varint,8,opt,name=grp_attn_w,json=grpAttnW,proto3" json:"grp_attn_w,omitempty"`
	// Print token count every n tokens (-1 = disabled)
	NPrint int32 `protobuf:"varint,9,opt,name=n_print,json=nPrint,proto3" json:"n_print,omitempty"`
	// RoPE base frequency
	RopeFreqBase float32 `protobuf:"fixed32,10,opt,name=rope_freq_base,json=ropeFreqBase,proto3" json:"rope_freq_base,omitempty"`
	// RoPE frequency scaling factor
	RopeFreqScale float32 `protobuf:"fixed32,11,opt,name=rope_freq_scale,json=ropeFreqScale,proto3" json:"rope_freq_scale,omitempty"`
	// YaRN extrapolation mix factor
	YarnExtFactor float32 `protobuf:"fixed32,12,opt,name=yarn_ext_factor,json=yarnExtFactor,proto3" json:"yarn_ext_factor,omitempty"`
	// YaRN magnitude scaling factor
	YarnAttnFactor float32 `protobuf:"fixed32,13,opt,name=yarn_attn_factor,json=yarnAttnFactor,proto3" json:"yarn_attn_factor,omitempty"`
	// YaRN low correction dim
	YarnBetaFast float32 `protobuf:"fixed32,14,opt,name=yarn_beta_fast,json=yarnBetaFast,proto3" json:"yarn_beta_fast,omitempty"`
	// YaRN high correction dim
	YarnBetaSlow float32 `protobuf:"fixed32,15,opt,name=yarn_beta_slow,json=yarnBetaSlow,proto3" json:"yarn_beta_slow,omitempty"`
	// YaRN original context length
	YarnOrigCtx int32 `protobuf:"varint,16,opt,name=yarn_orig_ctx,json=yarnOrigCtx,proto3" json:"yarn_orig_ctx,omitempty"`
	// KV cache defragmentation threshold
	DefragThold float32 `protobuf:"fixed32,17,opt,name=defrag_thold,json=defragThold,proto3" json:"defrag_thold,omitempty"`
	// Number of layers to store in VRAM (-1 = use default)
	NGpuLayers int32 `protobuf:"varint,18,opt,name=n_gpu_layers,json=nGpuLayers,proto3" json:"n_gpu_layers,omitempty"`
	// The GPU that is used for scratch and small tensors
	MainGpu int32 `protobuf:"varint,19,opt,name=main_gpu,json=mainGpu,proto3" json:"main_gpu,omitempty"`
	// Temperature for sampling
	Temperature float32 `protobuf:"fixed32,20,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Top-k sampling (0 = disabled)
	TopK int32 `protobuf:"varint,21,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// Top-p sampling (1.0 = disabled)
	TopP float32 `protobuf:"fixed32,22,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	// Min-p sampling (0.0 = disabled)
	MinP float32 `protobuf:"fixed32,23,opt,name=min_p,json=minP,proto3" json:"min_p,omitempty"`
	// Top-n-sigma sampling (-1.0 = disabled)
	TopNSigma float32 `protobuf:"fixed32,24,opt,name=top_n_sigma,json=topNSigma,proto3" json:"top_n_sigma,omitempty"`
	// Random number generator seed (-1 = random seed)
	Seed          uint32 `protobuf:"varint,25,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetNPredict() int32 {
	if x != nil {
		return x.NPredict
	}
	return 0
}

func (x *GenerateRequest) GetNCtx() int32 {
	if x != nil {
		return x.NCtx
	}
	return 0
}

func (x *GenerateRequest) GetNBatch() int32 {
	if x != nil {
		return x.NBatch
	}
	return 0
}

func (x *GenerateRequest) GetNKeep() int32 {
	if x != nil {
		return x.NKeep
	}
	return 0
}

func (x *GenerateRequest) GetNParallel() int32 {
	if x != nil {
		return x.NParallel
	}
	return 0
}

func (x *GenerateRequest) GetGrpAttnN() int32 {
	if x != nil {
		return x.GrpAttnN
	}
	return 0
}

func (x *GenerateRequest) GetGrpAttnW() int32 {
	if x != nil {
		return x.GrpAttnW
	}
	return 0
}

func (x *GenerateRequest) GetNPrint() int32 {
	if x != nil {
		return x.NPrint
	}
	return 0
}

func (x *GenerateRequest) GetRopeFreqBase() float32 {
	if x != nil {
		return x.RopeFreqBase
	}
	return 0
}

func (x *GenerateRequest) GetRopeFreqScale() float32 {
	if x != nil {
		return x.RopeFreqScale
	}
	return 0
}

func (x *GenerateRequest) GetYarnExtFactor() float32 {
	if x != nil {
		return x.YarnExtFactor
	}
	return 0
}

func (x *GenerateRequest) GetYarnAttnFactor() float32 {
	if x != nil {
		return x.YarnAttnFactor
	}
	return 0
}

func (x *GenerateRequest) GetYarnBetaFast() float32 {
	if x != nil {
		return x.YarnBetaFast
	}
	return 0
}

func (x *GenerateRequest) GetYarnBetaSlow() float32 {
	if x != nil {
		return x.YarnBetaSlow
	}
	return 0
}

func (x *GenerateRequest) GetYarnOrigCtx() int32 {
	if x != nil {
		return x.YarnOrigCtx
	}
	return 0
}

func (x *GenerateRequest) GetDefragThold() float32 {
	if x != nil {
		return x.DefragThold
	}
	return 0
}

func (x *GenerateRequest) GetNGpuLayers() int32 {
	if x != nil {
		return x.NGpuLayers
	}
	return 0
}

func (x *GenerateRequest) GetMainGpu() int32 {
	if x != nil {
		return x.MainGpu
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *GenerateRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GenerateRequest) GetMinP() float32 {
	if x != nil {
		return x.MinP
	}
	return 0
}

func (x *GenerateRequest) GetTopNSigma() float32 {
	if x != nil {
		return x.TopNSigma
	}
	return 0
}

func (x *GenerateRequest) GetSeed() uint32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_generate_proto protoreflect.FileDescriptor

const file_generate_proto_rawDesc = "" +
	"\n" +
	"\x0egenerate.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"\x84\x06\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1b\n" +
	"\tn_predict\x18\x02 \x01(\x05R\bnPredict\x12\x13\n" +
	"\x05n_ctx\x18\x03 \x01(\x05R\x04nCtx\x12\x17\n" +
	"\an_batch\x18\x04 \x01(\x05R\x06nBatch\x12\x15\n" +
	"\x06n_keep\x18\x05 \x01(\x05R\x05nKeep\x12\x1d\n" +
	"\n" +
	"n_parallel\x18\x06 \x01(\x05R\tnParallel\x12\x1c\n" +
	"\n" +
	"grp_attn_n\x18\a \x01(\x05R\bgrpAttnN\x12\x1c\n" +
	"\n" +
	"grp_attn_w\x18\b \x01(\x05R\bgrpAttnW\x12\x17\n" +
	"\an_print\x18\t \x01(\x05R\x06nPrint\x12$\n" +
	"\x0erope_freq_base\x18\n" +
	" \x01(\x02R\fropeFreqBase\x12&\n" +
	"\x0frope_freq_scale\x18\v \x01(\x02R\rropeFreqScale\x12&\n" +
	"\x0fyarn_ext_factor\x18\f \x01(\x02R\ryarnExtFactor\x12(\n" +
	"\x10yarn_attn_factor\x18\r \x01(\x02R\x0eyarnAttnFactor\x12$\n" +
	"\x0eyarn_beta_fast\x18\x0e \x01(\x02R\fyarnBetaFast\x12$\n" +
	"\x0eyarn_beta_slow\x18\x0f \x01(\x02R\fyarnBetaSlow\x12\"\n" +
	"\ryarn_orig_ctx\x18\x10 \x01(\x05R\vyarnOrigCtx\x12!\n" +
	"\fdefrag_thold\x18\x11 \x01(\x02R\vdefragThold\x12 \n" +
	"\fn_gpu_layers\x18\x12 \x01(\x05R\n" +
	"nGpuLayers\x12\x19\n" +
	"\bmain_gpu\x18\x13 \x01(\x05R\amainGpu\x12 \n" +
	"\vtemperature\x18\x14 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_k\x18\x15 \x01(\x05R\x04topK\x12\x13\n" +
	"\x05top_p\x18\x16 \x01(\x02R\x04topP\x12\x13\n" +
	"\x05min_p\x18\x17 \x01(\x02R\x04minP\x12\x1e\n" +
	"\vtop_n_sigma\x18\x18 \x01(\x02R\ttopNSigma\x12\x12\n" +
	"\x04seed\x18\x19 \x01(\rR\x04seed\",\n" +
	"\x10GenerateResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2`\n" +
	"\bGenerate\x12T\n" +
	"\bGenerate\x12\x16.proto.GenerateRequest\x1a\x17.proto.GenerateResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/generateB(Z&github.com/Qitmeer/llama.go/grpc/protob\x06proto3"

var (
	file_generate_proto_rawDescOnce sync.Once
	file_generate_proto_rawDescData []byte
)

func file_generate_proto_rawDescGZIP() []byte {
	file_generate_proto_rawDescOnce.Do(func() {
		file_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)))
	})
	return file_generate_proto_rawDescData
}

var file_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generate_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: proto.GenerateRequest
	(*GenerateResponse)(nil), // 1: proto.GenerateResponse
}
var file_generate_proto_depIdxs = []int32{
	0, // 0: proto.Generate.Generate:input_type -> proto.GenerateRequest
	1, // 1: proto.Generate.Generate:output_type -> proto.GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_generate_proto_init() }
func file_generate_proto_init() {
	if File_generate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_goTypes,
		DependencyIndexes: file_generate_proto_depIdxs,
		MessageInfos:      file_generate_proto_msgTypes,
	}.Build()
	File_generate_proto = out.File
	file_generate_proto_goTypes = nil
	file_generate_proto_depIdxs = nil
}
